#
# Copyright (c) 2023 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/herdstat/herdstat.
#
# SPDX-License-Identifier: MIT
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: ^CHANGELOG.md|3RD-PARTY-LICENSES/.*$
      - id: trailing-whitespace
        exclude: ^CHANGELOG.md|3RD-PARTY-LICENSES/.*$
      - id: mixed-line-ending
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.3.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        additional_dependencies:
          - '@commitlint/config-conventional'
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        args: [ -w ] # Update source files directly
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args:
          - --wrap
          - "120"
        additional_dependencies:
          - mdformat-gfm
        exclude: ^CHANGELOG.md|3RD-PARTY-LICENSES/.*$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        exclude: ^CHANGELOG.md|3RD-PARTY-LICENSES/.*$
